##############################################################################################
############################### DataSource properties ########################################
##############################################################################################
spring:
  datasource:
    #    schema : classpath:init-sql/schema.sql
    #    data: classpath:init-sql/data.sql
    continue-on-error : true
    name: master
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    url : jdbc:oracle:thin:@localhost:1521:orcl
    username: spring
    password: spring
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x' from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    ##############################################################################################
    ############################### 自定义 properties ########################################
    ##############################################################################################
    zipkin:
      base-url: http://localhost:9411
    sleuth:
      sampler:
      #采样率值介于 0 到 1 之间，1 则表示全部采集
      probability: 1
##############################################################################################
############################# spring boot Mybatis config #####################################
##############################################################################################
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: cn.itspring.cloud.entity    # 所有Entity别名类所在包
